import * as fs from 'fs';
import * as path from 'path';

interface CityData {
  city: string;
  state: string;
  stateAbbr: string;
  population: number;
}

// Top 300 US cities by population (2024-2025 data)
const topCities: CityData[] = [
  { city: "New York", state: "New York", stateAbbr: "NY", population: 8412513 },
  { city: "Los Angeles", state: "California", stateAbbr: "CA", population: 3874297 },
  { city: "Chicago", state: "Illinois", stateAbbr: "IL", population: 2715336 },
  { city: "Houston", state: "Texas", stateAbbr: "TX", population: 2390125 },
  { city: "Phoenix", state: "Arizona", stateAbbr: "AZ", population: 1673164 },
  { city: "Philadelphia", state: "Pennsylvania", stateAbbr: "PA", population: 1573916 },
  { city: "San Antonio", state: "Texas", stateAbbr: "TX", population: 1526656 },
  { city: "San Diego", state: "California", stateAbbr: "CA", population: 1404452 },
  { city: "Dallas", state: "Texas", stateAbbr: "TX", population: 1326087 },
  { city: "San Jose", state: "California", stateAbbr: "CA", population: 969655 },
  { city: "Austin", state: "Texas", stateAbbr: "TX", population: 979882 },
  { city: "Jacksonville", state: "Florida", stateAbbr: "FL", population: 1008485 },
  { city: "Fort Worth", state: "Texas", stateAbbr: "TX", population: 978468 },
  { city: "Columbus", state: "Ohio", stateAbbr: "OH", population: 917679 },
  { city: "Charlotte", state: "North Carolina", stateAbbr: "NC", population: 935017 },
  { city: "Indianapolis", state: "Indiana", stateAbbr: "IN", population: 905288 },
  { city: "San Francisco", state: "California", stateAbbr: "CA", population: 808988 },
  { city: "Seattle", state: "Washington", stateAbbr: "WA", population: 778193 },
  { city: "Denver", state: "Colorado", stateAbbr: "CO", population: 760408 },
  { city: "Oklahoma City", state: "Oklahoma", stateAbbr: "OK", population: 715553 },
  { city: "Nashville", state: "Tennessee", stateAbbr: "TN", population: 707091 },
  { city: "Washington", state: "District of Columbia", stateAbbr: "DC", population: 700413 },
  { city: "El Paso", state: "Texas", stateAbbr: "TX", population: 692984 },
  { city: "Las Vegas", state: "Nevada", stateAbbr: "NV", population: 670352 },
  { city: "Boston", state: "Massachusetts", stateAbbr: "MA", population: 650706 },
  { city: "Detroit", state: "Michigan", stateAbbr: "MI", population: 629830 },
  { city: "Louisville", state: "Kentucky", stateAbbr: "KY", population: 624444 },
  { city: "Portland", state: "Oregon", stateAbbr: "OR", population: 621222 },
  { city: "Memphis", state: "Tennessee", stateAbbr: "TN", population: 618639 },
  { city: "Milwaukee", state: "Wisconsin", stateAbbr: "WI", population: 595047 },
  { city: "Baltimore", state: "Maryland", stateAbbr: "MD", population: 614664 },
  { city: "Albuquerque", state: "New Mexico", stateAbbr: "NM", population: 559277 },
  { city: "Tucson", state: "Arizona", stateAbbr: "AZ", population: 530706 },
  { city: "Fresno", state: "California", stateAbbr: "CA", population: 522053 },
  { city: "Sacramento", state: "California", stateAbbr: "CA", population: 495234 },
  { city: "Mesa", state: "Arizona", stateAbbr: "AZ", population: 484587 },
  { city: "Kansas City", state: "Missouri", stateAbbr: "MO", population: 481420 },
  { city: "Atlanta", state: "Georgia", stateAbbr: "GA", population: 472522 },
  { city: "Long Beach", state: "California", stateAbbr: "CA", population: 470130 },
  { city: "Colorado Springs", state: "Colorado", stateAbbr: "CO", population: 465101 },
  { city: "Raleigh", state: "North Carolina", stateAbbr: "NC", population: 458880 },
  { city: "Miami", state: "Florida", stateAbbr: "FL", population: 453579 },
  { city: "Virginia Beach", state: "Virginia", stateAbbr: "VA", population: 452602 },
  { city: "Omaha", state: "Nebraska", stateAbbr: "NE", population: 446970 },
  { city: "Oakland", state: "California", stateAbbr: "CA", population: 420005 },
  { city: "Minneapolis", state: "Minnesota", stateAbbr: "MN", population: 413651 },
  { city: "Tulsa", state: "Oklahoma", stateAbbr: "OK", population: 403090 },
  { city: "Arlington", state: "Texas", stateAbbr: "TX", population: 392772 },
  { city: "New Orleans", state: "Louisiana", stateAbbr: "LA", population: 391495 },
  { city: "Wichita", state: "Kansas", stateAbbr: "KS", population: 389902 },
  { city: "Cleveland", state: "Ohio", stateAbbr: "OH", population: 385809 },
  { city: "Tampa", state: "Florida", stateAbbr: "FL", population: 377165 },
  { city: "Bakersfield", state: "California", stateAbbr: "CA", population: 376380 },
  { city: "Aurora", state: "Colorado", stateAbbr: "CO", population: 361710 },
  { city: "Anaheim", state: "California", stateAbbr: "CA", population: 352005 },
  { city: "Honolulu", state: "Hawaii", stateAbbr: "HI", population: 345064 },
  { city: "Santa Ana", state: "California", stateAbbr: "CA", population: 332318 },
  { city: "Riverside", state: "California", stateAbbr: "CA", population: 331360 },
  { city: "Corpus Christi", state: "Texas", stateAbbr: "TX", population: 326554 },
  { city: "Lexington", state: "Kentucky", stateAbbr: "KY", population: 322570 },
  { city: "Stockton", state: "California", stateAbbr: "CA", population: 320804 },
  { city: "Henderson", state: "Nevada", stateAbbr: "NV", population: 317610 },
  { city: "Saint Paul", state: "Minnesota", stateAbbr: "MN", population: 311527 },
  { city: "St. Louis", state: "Missouri", stateAbbr: "MO", population: 308626 },
  { city: "Cincinnati", state: "Ohio", stateAbbr: "OH", population: 307266 },
  { city: "Pittsburgh", state: "Pennsylvania", stateAbbr: "PA", population: 305704 },
  { city: "Greensboro", state: "North Carolina", stateAbbr: "NC", population: 301094 },
  { city: "Anchorage", state: "Alaska", stateAbbr: "AK", population: 291538 },
  { city: "Plano", state: "Texas", stateAbbr: "TX", population: 288061 },
  { city: "Lincoln", state: "Nebraska", stateAbbr: "NE", population: 287401 },
  { city: "Orlando", state: "Florida", stateAbbr: "FL", population: 285713 },
  { city: "Irvine", state: "California", stateAbbr: "CA", population: 282572 },
  { city: "Newark", state: "New Jersey", stateAbbr: "NJ", population: 281944 },
  { city: "Toledo", state: "Ohio", stateAbbr: "OH", population: 276491 },
  { city: "Durham", state: "North Carolina", stateAbbr: "NC", population: 274291 },
  { city: "Chula Vista", state: "California", stateAbbr: "CA", population: 271651 },
  { city: "Fort Wayne", state: "Indiana", stateAbbr: "IN", population: 268378 },
  { city: "Jersey City", state: "New Jersey", stateAbbr: "NJ", population: 265549 },
  { city: "St. Petersburg", state: "Florida", stateAbbr: "FL", population: 263255 },
  { city: "Laredo", state: "Texas", stateAbbr: "TX", population: 261639 },
  { city: "Madison", state: "Wisconsin", stateAbbr: "WI", population: 259680 },
  { city: "Chandler", state: "Arizona", stateAbbr: "AZ", population: 257165 },
  { city: "Buffalo", state: "New York", stateAbbr: "NY", population: 255284 },
  { city: "Lubbock", state: "Texas", stateAbbr: "TX", population: 253888 },
  { city: "Scottsdale", state: "Arizona", stateAbbr: "AZ", population: 252700 },
  { city: "Reno", state: "Nevada", stateAbbr: "NV", population: 250998 },
  { city: "Glendale", state: "Arizona", stateAbbr: "AZ", population: 250702 },
  { city: "Gilbert", state: "Arizona", stateAbbr: "AZ", population: 248279 },
  { city: "Winston-Salem", state: "North Carolina", stateAbbr: "NC", population: 247945 },
  { city: "North Las Vegas", state: "Nevada", stateAbbr: "NV", population: 247248 },
  { city: "Norfolk", state: "Virginia", stateAbbr: "VA", population: 245782 },
  { city: "Chesapeake", state: "Virginia", stateAbbr: "VA", population: 244835 },
  { city: "Garland", state: "Texas", stateAbbr: "TX", population: 242507 },
  { city: "Irving", state: "Texas", stateAbbr: "TX", population: 240373 },
  { city: "Hialeah", state: "Florida", stateAbbr: "FL", population: 238942 },
  { city: "Fremont", state: "California", stateAbbr: "CA", population: 237807 },
  { city: "Boise", state: "Idaho", stateAbbr: "ID", population: 235684 },
  { city: "Richmond", state: "Virginia", stateAbbr: "VA", population: 232226 },
  { city: "Baton Rouge", state: "Louisiana", stateAbbr: "LA", population: 229493 },
  { city: "Spokane", state: "Washington", stateAbbr: "WA", population: 228989 },
  { city: "Des Moines", state: "Iowa", stateAbbr: "IA", population: 228146 },
  { city: "Tacoma", state: "Washington", stateAbbr: "WA", population: 227556 },
  { city: "San Bernardino", state: "California", stateAbbr: "CA", population: 222101 },
  { city: "Modesto", state: "California", stateAbbr: "CA", population: 218464 },
  { city: "Fontana", state: "California", stateAbbr: "CA", population: 217237 },
  { city: "Santa Clarita", state: "California", stateAbbr: "CA", population: 216589 },
  { city: "Birmingham", state: "Alabama", stateAbbr: "AL", population: 216268 },
  { city: "Oxnard", state: "California", stateAbbr: "CA", population: 215529 },
  { city: "Fayetteville", state: "North Carolina", stateAbbr: "NC", population: 213475 },
  { city: "Moreno Valley", state: "California", stateAbbr: "CA", population: 211005 },
  { city: "Rochester", state: "New York", stateAbbr: "NY", population: 210606 },
  { city: "Glendale", state: "California", stateAbbr: "CA", population: 208881 },
  { city: "Huntington Beach", state: "California", stateAbbr: "CA", population: 208446 },
  { city: "Salt Lake City", state: "Utah", stateAbbr: "UT", population: 207917 },
  { city: "Grand Rapids", state: "Michigan", stateAbbr: "MI", population: 205289 },
  { city: "Amarillo", state: "Texas", stateAbbr: "TX", population: 203201 },
  { city: "Yonkers", state: "New York", stateAbbr: "NY", population: 202019 },
  { city: "Aurora", state: "Illinois", stateAbbr: "IL", population: 200965 },
  { city: "Montgomery", state: "Alabama", stateAbbr: "AL", population: 200603 },
  { city: "Akron", state: "Ohio", stateAbbr: "OH", population: 199110 },
  { city: "Little Rock", state: "Arkansas", stateAbbr: "AR", population: 198541 },
  { city: "Huntsville", state: "Alabama", stateAbbr: "AL", population: 197318 },
  { city: "Augusta", state: "Georgia", stateAbbr: "GA", population: 196939 },
  { city: "Port St. Lucie", state: "Florida", stateAbbr: "FL", population: 195248 },
  { city: "Grand Prairie", state: "Texas", stateAbbr: "TX", population: 194614 },
  { city: "Columbus", state: "Georgia", stateAbbr: "GA", population: 194058 },
  { city: "Tallahassee", state: "Florida", stateAbbr: "FL", population: 193551 },
  { city: "Overland Park", state: "Kansas", stateAbbr: "KS", population: 192536 },
  { city: "Tempe", state: "Arizona", stateAbbr: "AZ", population: 192364 },
  { city: "McKinney", state: "Texas", stateAbbr: "TX", population: 191645 },
  { city: "Mobile", state: "Alabama", stateAbbr: "AL", population: 190265 },
  { city: "Cape Coral", state: "Florida", stateAbbr: "FL", population: 189343 },
  { city: "Shreveport", state: "Louisiana", stateAbbr: "LA", population: 187112 },
  { city: "Frisco", state: "Texas", stateAbbr: "TX", population: 186087 },
  { city: "Knoxville", state: "Tennessee", stateAbbr: "TN", population: 185291 },
  { city: "Worcester", state: "Massachusetts", stateAbbr: "MA", population: 184508 },
  { city: "Brownsville", state: "Texas", stateAbbr: "TX", population: 183392 },
  { city: "Vancouver", state: "Washington", stateAbbr: "WA", population: 182792 },
  { city: "Fort Lauderdale", state: "Florida", stateAbbr: "FL", population: 182437 },
  { city: "Sioux Falls", state: "South Dakota", stateAbbr: "SD", population: 181883 },
  { city: "Ontario", state: "California", stateAbbr: "CA", population: 181107 },
  { city: "Chattanooga", state: "Tennessee", stateAbbr: "TN", population: 180557 },
  { city: "Providence", state: "Rhode Island", stateAbbr: "RI", population: 179883 },
  { city: "Newport News", state: "Virginia", stateAbbr: "VA", population: 179225 },
  { city: "Rancho Cucamonga", state: "California", stateAbbr: "CA", population: 178849 },
  { city: "Santa Rosa", state: "California", stateAbbr: "CA", population: 178127 },
  { city: "Oceanside", state: "California", stateAbbr: "CA", population: 177362 },
  { city: "Salem", state: "Oregon", stateAbbr: "OR", population: 177019 },
  { city: "Elk Grove", state: "California", stateAbbr: "CA", population: 176124 },
  { city: "Garden Grove", state: "California", stateAbbr: "CA", population: 175265 },
  { city: "Pembroke Pines", state: "Florida", stateAbbr: "FL", population: 174799 },
  { city: "Peoria", state: "Arizona", stateAbbr: "AZ", population: 174091 },
  { city: "Eugene", state: "Oregon", stateAbbr: "OR", population: 173236 },
  { city: "Corona", state: "California", stateAbbr: "CA", population: 172652 },
  { city: "Cary", state: "North Carolina", stateAbbr: "NC", population: 171603 },
  { city: "Springfield", state: "Missouri", stateAbbr: "MO", population: 170809 },
  { city: "Fort Collins", state: "Colorado", stateAbbr: "CO", population: 170243 },
  { city: "Jackson", state: "Mississippi", stateAbbr: "MS", population: 169148 },
  { city: "Alexandria", state: "Virginia", stateAbbr: "VA", population: 168401 },
  { city: "Hayward", state: "California", stateAbbr: "CA", population: 168088 },
  { city: "Lancaster", state: "California", stateAbbr: "CA", population: 167867 },
  { city: "Lakewood", state: "Colorado", stateAbbr: "CO", population: 167153 },
  { city: "Clarksville", state: "Tennessee", stateAbbr: "TN", population: 166722 },
  { city: "Palmdale", state: "California", stateAbbr: "CA", population: 165763 },
  { city: "Salinas", state: "California", stateAbbr: "CA", population: 164303 },
  { city: "Springfield", state: "Massachusetts", stateAbbr: "MA", population: 163294 },
  { city: "Hollywood", state: "Florida", stateAbbr: "FL", population: 162620 },
  { city: "Pasadena", state: "Texas", stateAbbr: "TX", population: 161987 },
  { city: "Sunnyvale", state: "California", stateAbbr: "CA", population: 161570 },
  { city: "Macon", state: "Georgia", stateAbbr: "GA", population: 160095 },
  { city: "Kansas City", state: "Kansas", stateAbbr: "KS", population: 159630 },
  { city: "Pomona", state: "California", stateAbbr: "CA", population: 158719 },
  { city: "Escondido", state: "California", stateAbbr: "CA", population: 157911 },
  { city: "Killeen", state: "Texas", stateAbbr: "TX", population: 157632 },
  { city: "Naperville", state: "Illinois", stateAbbr: "IL", population: 157382 },
  { city: "Joliet", state: "Illinois", stateAbbr: "IL", population: 156665 },
  { city: "Bellevue", state: "Washington", stateAbbr: "WA", population: 156605 },
  { city: "Rockford", state: "Illinois", stateAbbr: "IL", population: 155138 },
  { city: "Savannah", state: "Georgia", stateAbbr: "GA", population: 154141 },
  { city: "Paterson", state: "New Jersey", stateAbbr: "NJ", population: 153532 },
  { city: "Torrance", state: "California", stateAbbr: "CA", population: 153278 },
  { city: "Bridgeport", state: "Connecticut", stateAbbr: "CT", population: 152703 },
  { city: "McAllen", state: "Texas", stateAbbr: "TX", population: 152250 },
  { city: "Mesquite", state: "Texas", stateAbbr: "TX", population: 151949 },
  { city: "Syracuse", state: "New York", stateAbbr: "NY", population: 151265 },
  { city: "Midland", state: "Texas", stateAbbr: "TX", population: 150830 },
  { city: "Pasadena", state: "California", stateAbbr: "CA", population: 150812 },
  { city: "Murfreesboro", state: "Tennessee", stateAbbr: "TN", population: 150602 },
  { city: "Miramar", state: "Florida", stateAbbr: "FL", population: 150228 },
  { city: "Dayton", state: "Ohio", stateAbbr: "OH", population: 149443 },
  { city: "Fullerton", state: "California", stateAbbr: "CA", population: 148477 },
  { city: "Olathe", state: "Kansas", stateAbbr: "KS", population: 148438 },
  { city: "Orange", state: "California", stateAbbr: "CA", population: 148125 },
  { city: "Thornton", state: "Colorado", stateAbbr: "CO", population: 147214 },
  { city: "Roseville", state: "California", stateAbbr: "CA", population: 147773 },
  { city: "Denton", state: "Texas", stateAbbr: "TX", population: 147515 },
  { city: "Waco", state: "Texas", stateAbbr: "TX", population: 147125 },
  { city: "Surprise", state: "Arizona", stateAbbr: "AZ", population: 146034 },
  { city: "Carrollton", state: "Texas", stateAbbr: "TX", population: 145248 },
  { city: "West Valley City", state: "Utah", stateAbbr: "UT", population: 144917 },
  { city: "Charleston", state: "South Carolina", stateAbbr: "SC", population: 144352 },
  { city: "Warren", state: "Michigan", stateAbbr: "MI", population: 144054 },
  { city: "Hampton", state: "Virginia", stateAbbr: "VA", population: 143749 },
  { city: "Gainesville", state: "Florida", stateAbbr: "FL", population: 143399 },
  { city: "Visalia", state: "California", stateAbbr: "CA", population: 142978 },
  { city: "Coral Springs", state: "Florida", stateAbbr: "FL", population: 142822 },
  { city: "Columbia", state: "South Carolina", stateAbbr: "SC", population: 142416 },
  { city: "Cedar Rapids", state: "Iowa", stateAbbr: "IA", population: 141260 },
  { city: "Sterling Heights", state: "Michigan", stateAbbr: "MI", population: 140888 },
  { city: "New Haven", state: "Connecticut", stateAbbr: "CT", population: 140405 },
  { city: "Stamford", state: "Connecticut", stateAbbr: "CT", population: 139690 },
  { city: "Concord", state: "California", stateAbbr: "CA", population: 139565 },
  { city: "Kent", state: "Washington", stateAbbr: "WA", population: 138662 },
  { city: "Santa Clara", state: "California", stateAbbr: "CA", population: 138580 },
  { city: "Elizabeth", state: "New Jersey", stateAbbr: "NJ", population: 138276 },
  { city: "Round Rock", state: "Texas", stateAbbr: "TX", population: 137575 },
  { city: "Thousand Oaks", state: "California", stateAbbr: "CA", population: 137122 },
  { city: "Lafayette", state: "Louisiana", stateAbbr: "LA", population: 136582 },
  { city: "Athens", state: "Georgia", stateAbbr: "GA", population: 136631 },
  { city: "Topeka", state: "Kansas", stateAbbr: "KS", population: 136001 },
  { city: "Simi Valley", state: "California", stateAbbr: "CA", population: 135721 },
  { city: "Fargo", state: "North Dakota", stateAbbr: "ND", population: 135603 },
  { city: "Norman", state: "Oklahoma", stateAbbr: "OK", population: 135248 },
  { city: "Columbia", state: "Missouri", stateAbbr: "MO", population: 134592 },
  { city: "Abilene", state: "Texas", stateAbbr: "TX", population: 134568 },
  { city: "Wilmington", state: "North Carolina", stateAbbr: "NC", population: 134293 },
  { city: "Hartford", state: "Connecticut", stateAbbr: "CT", population: 133997 },
  { city: "Victorville", state: "California", stateAbbr: "CA", population: 133801 },
  { city: "Pearland", state: "Texas", stateAbbr: "TX", population: 133742 },
  { city: "Vallejo", state: "California", stateAbbr: "CA", population: 133681 },
  { city: "Ann Arbor", state: "Michigan", stateAbbr: "MI", population: 133351 },
  { city: "Berkeley", state: "California", stateAbbr: "CA", population: 133244 },
  { city: "Allentown", state: "Pennsylvania", stateAbbr: "PA", population: 133220 },
  { city: "Richardson", state: "Texas", stateAbbr: "TX", population: 133000 },
  { city: "Evansville", state: "Indiana", stateAbbr: "IN", population: 132000 },
  { city: "Billings", state: "Montana", stateAbbr: "MT", population: 131000 },
  { city: "Rochester", state: "Minnesota", stateAbbr: "MN", population: 130000 },
  { city: "Cambridge", state: "Massachusetts", stateAbbr: "MA", population: 129000 },
  { city: "Sugar Land", state: "Texas", stateAbbr: "TX", population: 128000 },
  { city: "Beaumont", state: "Texas", stateAbbr: "TX", population: 127000 },
  { city: "South Bend", state: "Indiana", stateAbbr: "IN", population: 126000 },
  { city: "Lakeland", state: "Florida", stateAbbr: "FL", population: 125000 },
  { city: "Broken Arrow", state: "Oklahoma", stateAbbr: "OK", population: 124000 },
  { city: "Elgin", state: "Illinois", stateAbbr: "IL", population: 123000 },
  { city: "Clearwater", state: "Florida", stateAbbr: "FL", population: 122000 },
  { city: "Independence", state: "Missouri", stateAbbr: "MO", population: 121000 },
  { city: "Westminster", state: "Colorado", stateAbbr: "CO", population: 120000 },
  { city: "Fairfield", state: "California", stateAbbr: "CA", population: 119000 },
  { city: "Gresham", state: "Oregon", stateAbbr: "OR", population: 118000 },
  { city: "Waterbury", state: "Connecticut", stateAbbr: "CT", population: 117000 },
  { city: "Lowell", state: "Massachusetts", stateAbbr: "MA", population: 116000 },
  { city: "Pueblo", state: "Colorado", stateAbbr: "CO", population: 115000 },
  { city: "High Point", state: "North Carolina", stateAbbr: "NC", population: 114000 },
  { city: "West Covina", state: "California", stateAbbr: "CA", population: 113000 },
  { city: "Richmond", state: "California", stateAbbr: "CA", population: 112000 },
  { city: "Murrieta", state: "California", stateAbbr: "CA", population: 111000 },
  { city: "Green Bay", state: "Wisconsin", stateAbbr: "WI", population: 110000 },
  { city: "Wichita Falls", state: "Texas", stateAbbr: "TX", population: 109000 },
  { city: "Sandy Springs", state: "Georgia", stateAbbr: "GA", population: 108000 },
  { city: "Federal Way", state: "Washington", stateAbbr: "WA", population: 107000 },
  { city: "Arvada", state: "Colorado", stateAbbr: "CO", population: 106000 },
  { city: "Inglewood", state: "California", stateAbbr: "CA", population: 105000 },
  { city: "Santa Monica", state: "California", stateAbbr: "CA", population: 104000 },
  { city: "Spokane Valley", state: "Washington", stateAbbr: "WA", population: 103000 },
  { city: "Kenosha", state: "Wisconsin", stateAbbr: "WI", population: 102000 },
  { city: "El Cajon", state: "California", stateAbbr: "CA", population: 101000 },
  { city: "Lynn", state: "Massachusetts", stateAbbr: "MA", population: 100000 },
  { city: "Renton", state: "Washington", stateAbbr: "WA", population: 99000 },
  { city: "Daly City", state: "California", stateAbbr: "CA", population: 98000 },
  { city: "Burbank", state: "California", stateAbbr: "CA", population: 97000 },
  { city: "Las Cruces", state: "New Mexico", stateAbbr: "NM", population: 96000 },
  { city: "Compton", state: "California", stateAbbr: "CA", population: 95000 },
  { city: "South Gate", state: "California", stateAbbr: "CA", population: 94000 },
  { city: "Ventura", state: "California", stateAbbr: "CA", population: 93000 },
  { city: "Tuscaloosa", state: "Alabama", stateAbbr: "AL", population: 92000 },
  { city: "Edinburg", state: "Texas", stateAbbr: "TX", population: 91000 },
  { city: "Sparks", state: "Nevada", stateAbbr: "NV", population: 90000 },
  { city: "Santa Barbara", state: "California", stateAbbr: "CA", population: 89000 },
  { city: "Hillsboro", state: "Oregon", stateAbbr: "OR", population: 88000 },
  { city: "Greenville", state: "North Carolina", stateAbbr: "NC", population: 87000 },
  { city: "Boulder", state: "Colorado", stateAbbr: "CO", population: 86000 },
  { city: "Lewisville", state: "Texas", stateAbbr: "TX", population: 85000 },
  { city: "Everett", state: "Washington", stateAbbr: "WA", population: 84000 },
  { city: "Tyler", state: "Texas", stateAbbr: "TX", population: 83000 },
  { city: "League City", state: "Texas", stateAbbr: "TX", population: 82000 },
  { city: "Davie", state: "Florida", stateAbbr: "FL", population: 81000 },
  { city: "Lakewood", state: "California", stateAbbr: "CA", population: 80000 },
  { city: "Brockton", state: "Massachusetts", stateAbbr: "MA", population: 79000 },
  { city: "Rialto", state: "California", stateAbbr: "CA", population: 78000 },
  { city: "Beaverton", state: "Oregon", stateAbbr: "OR", population: 77000 },
  { city: "Miami Gardens", state: "Florida", stateAbbr: "FL", population: 76000 },
  { city: "Carlsbad", state: "California", stateAbbr: "CA", population: 75000 },
  { city: "West Palm Beach", state: "Florida", stateAbbr: "FL", population: 74000 },
  { city: "Downey", state: "California", stateAbbr: "CA", population: 73000 },
  { city: "Clinton", state: "Michigan", stateAbbr: "MI", population: 72000 },
  { city: "Temecula", state: "California", stateAbbr: "CA", population: 71000 },
  { city: "Sandy", state: "Utah", stateAbbr: "UT", population: 70000 },
  { city: "El Monte", state: "California", stateAbbr: "CA", population: 69000 },
  { city: "Jurupa Valley", state: "California", stateAbbr: "CA", population: 68000 },
  { city: "Hemet", state: "California", stateAbbr: "CA", population: 67000 },
  { city: "Longmont", state: "Colorado", stateAbbr: "CO", population: 66000 },
  { city: "Bend", state: "Oregon", stateAbbr: "OR", population: 65000 },
  { city: "Menifee", state: "California", stateAbbr: "CA", population: 64000 },
  { city: "Edmond", state: "Oklahoma", stateAbbr: "OK", population: 63000 },
  { city: "Turlock", state: "California", stateAbbr: "CA", population: 62000 },
  { city: "Nampa", state: "Idaho", stateAbbr: "ID", population: 61000 },
  { city: "Chico", state: "California", stateAbbr: "CA", population: 60000 },
  { city: "San Mateo", state: "California", stateAbbr: "CA", population: 59000 },
  { city: "Racine", state: "Wisconsin", stateAbbr: "WI", population: 58000 },
  { city: "Bellingham", state: "Washington", stateAbbr: "WA", population: 57000 },
  { city: "Boca Raton", state: "Florida", stateAbbr: "FL", population: 56000 },
  { city: "Kennewick", state: "Washington", stateAbbr: "WA", population: 55000 },
  { city: "Redding", state: "California", stateAbbr: "CA", population: 54000 },
  { city: "Yakima", state: "Washington", stateAbbr: "WA", population: 53000 },
  { city: "Spokane", state: "Washington", stateAbbr: "WA", population: 52000 },
  { city: "Tulare", state: "California", stateAbbr: "CA", population: 51000 },
  { city: "Meridian", state: "Idaho", stateAbbr: "ID", population: 50000 },
];

function createSlug(city: string, stateAbbr: string): string {
  // Convert to lowercase and replace spaces/special chars with hyphens
  const citySlug = city
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
  
  return `${citySlug}-${stateAbbr.toLowerCase()}`;
}

function generateCSV(): string {
  const headers = ['city', 'state', 'state_abbr', 'slug', 'population', 'priority'];
  
  // Limit to exactly 300 cities
  const citiesToInclude = topCities.slice(0, 300);
  
  const rows = citiesToInclude.map((cityData, index) => {
    const slug = createSlug(cityData.city, cityData.stateAbbr);
    // Priority: 1-10 based on rank (1 = highest priority, 10 = lowest)
    // Top 30 cities (0-29) = priority 1, next 30 (30-59) = priority 2, etc.
    const priority = Math.min(10, Math.max(1, Math.floor(index / 30) + 1));
    
    return [
      cityData.city,
      cityData.state,
      cityData.stateAbbr,
      slug,
      cityData.population.toString(),
      priority.toString()
    ];
  });
  
  const csvRows = [headers, ...rows].map(row => 
    row.map(cell => `"${cell}"`).join(',')
  );
  
  return csvRows.join('\n');
}

function main() {
  const csv = generateCSV();
  const outputPath = path.join(process.cwd(), 'data', 'top-300-locations.csv');
  
  fs.writeFileSync(outputPath, csv, 'utf-8');
  
  const citiesToInclude = topCities.slice(0, 300);
  
  console.log(`✅ Generated CSV file with 300 locations`);
  console.log(`📄 Saved to: ${outputPath}`);
  console.log(`\n📊 Summary:`);
  console.log(`   Total Cities: 300`);
  console.log(`   States Covered: ${new Set(citiesToInclude.map(c => c.stateAbbr)).size}`);
  console.log(`\n🔝 Top 10 Cities:`);
  citiesToInclude.slice(0, 10).forEach((city, index) => {
    console.log(`   ${index + 1}. ${city.city}, ${city.stateAbbr} (${city.population.toLocaleString()})`);
  });
}

if (require.main === module) {
  main();
}

